// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"firebase.google.com/go/v4/auth"
	"github.com/eclipse/paho.mqtt.golang"
	"gorm.io/gorm"
	"project-home-iot/internal/core/domain"
	"project-home-iot/internal/core/usecase"
	"project-home-iot/internal/firebase"
	gorm2 "project-home-iot/internal/infrastructure/gorm"
	"project-home-iot/internal/infrastructure/http"
	mqtt2 "project-home-iot/internal/infrastructure/mqtt"
)

// Injectors from wire.go:

func InitializeApp(db *gorm.DB, client mqtt.Client) (*AppHandlers, error) {
	authClient, err := firebase.NewFirebaseAuthClient()
	if err != nil {
		return nil, err
	}
	deviceRepository := gorm2.NewDeviceRepository(db)
	capabilityRepository := gorm2.NewCapabilityRepository(db)
	widgetRepository := gorm2.NewWidgetRepository(db)
	pairCommander := mqtt2.NewMQTTPairCommander(client)
	deviceUsecase := usecase.NewDeviceUsecase(deviceRepository, capabilityRepository, widgetRepository, pairCommander)
	deviceHandler := http.NewDeviceHandler(deviceUsecase)
	deviceCommander := mqtt2.NewMQTTDeviceCommander(client)
	recorderRepository := gorm2.NewRecorderRepository(db)
	commandUsecase := usecase.NewCommandUsecase(deviceRepository, widgetRepository, deviceCommander, recorderRepository)
	widgetUsecase := usecase.NewWidgetUsecase(widgetRepository, recorderRepository)
	commandHandler := http.NewCommandHandler(commandUsecase, widgetUsecase)
	roomRepository := gorm2.NewRoomRepository(db)
	roomUsecase := usecase.NewRoomUsecase(roomRepository, deviceRepository)
	roomHandler := http.NewRoomHandler(roomUsecase)
	widgetHandler := http.NewWidgetHandler(widgetUsecase)
	userRepository := gorm2.NewUserRepository(db)
	userUsecase := usecase.NewUserUsecase(userRepository, authClient)
	userHandler := http.NewUserHandler(userUsecase)
	mqttHandler := mqtt2.NewMQTTHandler(deviceUsecase, widgetUsecase)
	sensorSubscriber := mqtt2.NewSensorSubscriber(client)
	recordLogUsecase := usecase.NewRecordLogUsecase(recorderRepository, widgetRepository, capabilityRepository)
	sensorHandler := mqtt2.NewSensorHandler(recordLogUsecase, deviceUsecase, widgetUsecase)
	appHandlers := &AppHandlers{
		AuthClient:       authClient,
		Device:           deviceHandler,
		Command:          commandHandler,
		Room:             roomHandler,
		Widget:           widgetHandler,
		User:             userHandler,
		MQTT:             mqttHandler,
		SensorSubscriber: sensorSubscriber,
		SensorHandler:    sensorHandler,
		UserRepo:         userRepository,
	}
	return appHandlers, nil
}

// wire.go:

type AppHandlers struct {
	// Auth    *auth.AuthHandler
	AuthClient       *auth.Client
	Device           *http.DeviceHandler
	Command          *http.CommandHandler
	Room             *http.RoomHandler
	Widget           *http.WidgetHandler
	User             *http.UserHandler
	MQTT             *mqtt2.MQTTHandler
	SensorSubscriber *mqtt2.SensorSubscriber
	SensorHandler    *mqtt2.SensorHandler
	UserRepo         domain.UserRepository
}
