// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gorm.io/gorm"
	"project-home-iot/internal/auth"
)

// Injectors from wire.go:

func InitializeApp(db *gorm.DB) *AppHandlers {
	repository := auth.NewRepository(db)
	authService := auth.NewService(repository)
	authHandler := auth.NewAuthHandler(authService)
	appHandlers := &AppHandlers{
		Auth: authHandler,
	}
	return appHandlers
}

// wire.go:

type AppHandlers struct {
	Auth *auth.AuthHandler
}
